stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
      - src/data/data_ingestion.py
      - Given_Data/Urban Air Quality and Health Impact Dataset.csv

  data_cleaning:
    cmd: python src/data/data_cleaning.py
    deps:
      - src/data/data_cleaning.py
      - data/raw/raw.csv
  
  feature_engineering:
    cmd: python src/data/feature_engineering.py
    deps:
      - src/data/feature_engineering.py
      - data/raw/clean.csv
      - data/processed/process.csv

  data_transformation:
    cmd: python src/data/data_transformation.py
    deps:
      - src/data/data_transformation.py
      - data/processed/process.csv
  
  model_training:
    cmd: python src/models/train_model.py
    deps:
      - src/models/train_model.py
      - data/processed/train.npy
      - data/processed/test.npy
      - Models/model.pkl

  model_evulation:
    cmd: python src/tests/test_model.py
    deps:
      - data/processed/test.npy
      - Models/model.pkl
      - reports/model_report.json