name: project_CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
          
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Install DVC
        run: |
          pip install dvc
          pip install dvc[s3]

      - name: Restore tracked data files
        run: |
          dvc checkout

      - name: Pull data from DVC remote (if necessary)
        run: |
          dvc pull
      - name: Run DVC pipeline
        run: |
          dvc repro
